### ISSUE TITLE
Parse error: 

### ISSUE THREAD

**Issue by dcsorenson** [strangerstudios/pmpro-advanced-levels-shortcode#12]
syntax error, unexpected '}' in /home/dcsorenson63/public_html/wp-content/plugins/pmpro-advanced-levels-shortcode/templates/levels-compare_table.php on line 279

**Comment by eighty20results** [comment]
Bug fix has been submitted as a pull request. Pending review & release by @strangerstudios

**Comment by eighty20results** [comment]
https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/pull/13
