### ISSUE TITLE
Discount codes not recognized in URLs

### ISSUE THREAD

**Issue by accessallareas** [strangerstudios/pmpro-advanced-levels-shortcode#15]
If I link to a page with Advanced Levels Shortcode in the form of ?discount_code=CODE the code does not get recognized. As users usually don't link directly to a checkout page but to a product page or compare table this would be a very welcome feature.

**Comment by eighty20results** [comment]
Hi,

Thanks for reporting this.

What version of the add-on are you using? We just updated and pushed out an update to handle discount codes as shortcode arguments a day or two aga.

**Comment by accessallareas** [comment]
I'm using the latest update (2.3). However, I'm not talking about shortcode arguments (as in
[pmpro_advanced_levels levels="1,2,3" discount_code="CODE"]) but URL arguments (mypage.com?discount_code=CODE)

**Comment by eighty20results** [comment]
I guess I don't fully appreciate how/why it's of value to override whatever either the pmpro_levels or the pmpro_advanced_levels short codes generate for their select/checkout link buttons? 

After all, if you're bypassing the level(s) page, you don't need the add-on to handle the argument, and passing a discount code to the levels page doesn't matter as it's never processed there... The discount code is only processed on the checkout page, which you can always bypass with a direct link to the checkout page with the `levels=` and `discount_code=` parameters present, from wherever.

**Comment by accessallareas** [comment]
So, I have a blog or partner site or email newsletter that offers a discount for my membership site. "Click here to get 20 % off". This is a link like example.com?discount_code=20OFF. 
Where do you want the people to land? Definitely not on the checkout page but on the product page or compare table page, so they can see what they are buying into, compare their options (XL XXL or XXXL Package), see nice infographics etc. and then make their decision and proceed to checkout.

So it is essential that the levels page is able to read the URL attribute and display the reduced price instead of the regular price. 
You can't ask potential customers to re-enter information (like a coupon code) that is already there. And you can't make site-owners open a levels page for each coupon code that is around - if I have 20 codes I would need 20 level pages to have the corresponding discounted prices appear there.

**Comment by kimcoleman** [comment]
We should add $_REQUEST to get the discount code from the URL [here](https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/blob/dev/templates/levels.php#L51) if it is present and the shortcode otherwise has no discount code specified.

If discount code is specified in shortcode attributes, that one would always be used over any code in the URL.
