### ISSUE TITLE
make a "button" layout

### ISSUE THREAD

**Issue by accessallareas** [strangerstudios/pmpro-advanced-levels-shortcode#18]
I think it would be great to have a "button" layout, that contains button text and (if applicable) price. This would enable a high freedom in creating product/membership pages (eg more advanced compare tables etc) by still maintaining the great functionality of the plug-in.

**Comment by kimcoleman** [comment]
The core Paid Memberships Pro plugin has a shortcode for a [pmpro_checkout_button] documented here: https://www.paidmembershipspro.com/documentation/shortcodes/general-shortcodes/

There is also a block for the button documented here: https://www.paidmembershipspro.com/documentation/shortcodes/membership-blocks/
