### ISSUE TITLE
display "instead prices"

### ISSUE THREAD

**Issue by accessallareas** [strangerstudios/pmpro-advanced-levels-shortcode#20]
If a discount code is used, it would be great to be able to display the regular price as well as the discount price. Like 7.99 instead of 9.99. Or -9.99- (strike through) 7.99. So the potential customers see the benefit they're getting.

**Comment by kimcoleman** [comment]
This is possible with the Level Cost Text Add On. See: https://www.paidmembershipspro.com/add-ons/pmpro-custom-level-cost-text/
