### ISSUE TITLE
"Free" in compare_table in pmpro_level-price pmpro_level-current not translated

### ISSUE THREAD

**Issue by accessallareas** [strangerstudios/pmpro-advanced-levels-shortcode#21]
Translation file seems to ignore the "Free" under the Membership Level name in compare_table view.

**Comment by kimcoleman** [comment]
These lines should be updated to the proper text domain for the Add On and not use a core PMPro outdated textdomain. https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/blob/dev/templates/levels-compare_table.php#L37-L43

**Comment by kimcoleman** [comment]
There are actually a few places the textdomain is incorrect in this plugin. When working this issue the entire code in the Add On should be addressed and correct textdomain used.

**Comment by michaelbeil** [comment]
A [customer sent in a **support ticket (moderators only)**](https://www.paidmembershipspro.com/forums/topic/missing-string-for-translation/) with the following:  
>used the pmpro_advanced_levels shortcode and upon publishing the page see an English sentence: “Membership never expires”. Hmm … that string ain’t in glotdict. Happen to know cause I translated and manage the whole translation in Dutch. Please add.

**Comment by kimcoleman** [comment]
These strings are all now properly set up for translation using the plugin's text domain 'pmpro-advanced-levels-shortcode'.
