### ISSUE TITLE
Disable buttons for certain levels

### ISSUE THREAD

**Issue by accessallareas** [strangerstudios/pmpro-advanced-levels-shortcode#22]
I use advanced levels plugin in compare_table layout. I would like to show logged in users the different levels but only allow them to upgrade to higher levels. 
So I think it would create a lot of flexibility if users could disable buttons to certain levels completely. This could be old membership levels that are no longer offered or "lower" levels than the current level, so users can only upgrade, not downgrade.

**Comment by kimcoleman** [comment]
The best way to achieve this is by placing multiple shortcodes on the same page with only the proper upgrade levels. You can then use the [membership] shortcode to wrap your various custom levels layouts or place the advanced levels shortcode within the "Require Membership" block.
