### ISSUE TITLE
Code to show Member Badges not working in Compare Table Layout

### ISSUE THREAD

**Issue by MaryOJob** [strangerstudios/pmpro-advanced-levels-shortcode#31]
Steps to recreate:

- Add a shortcode to display pricing like this: [pmpro_advanced_levels levels="1,3,2" layout="3col" compare="Compare Item 1,1,1;Compare Item 2,1,1;Compare Item 3,1,1;Numerical Thing,10 Things,20 Things"]
- add [this code gist](https://gist.github.com/strangerstudios/6971fc87b780bfdd13724c27f97df796) to display member badges icon
- change layout attribute in the shortcode to compare_table and in the code gist to 'compare_table'
- member badge does not get displayed. change layout to Div, 4Col, or any other attribute, it works as intended.

**Comment by kimcoleman** [comment]
There are currently no hooks on the compare_table layout. We are planning to add a filter to the compare attribute that will allow any custom HTML or special characters. This new filter can be used for displaying the badge.
