### ISSUE TITLE
Issue: Unable to add Commas to output

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-advanced-levels-shortcode#36]
Appears to be a WordPress problem with using shortcodes.
Users are unable to add a comma "," to display text.  It will usually force a break to the next element.
Slash comma does not work and using HTML for comma will not work as it has a semicolon in it.

Example: can not display 10,000

**Comment by kimcoleman** [comment]
The next version will include a new filter to the compare_items - there is an example of using this filter here: https://gist.github.com/JarrydLong/bfa658a4654e62fae2773d284825bc81

For now this will be how we recommend using advanced HTML / code or characters like comma, apostrophe, quotes, or semicolon.
