### ISSUE TITLE
Feature request: Add a Gutenberg block

### ISSUE THREAD

**Issue by michaelbeil** [strangerstudios/pmpro-advanced-levels-shortcode#37]
**Feature request**

A customer sent in ticket (id 284341) with the following question:  
>can we expect a gutenberg block for advanced levels next to shortcode?

**Additional context** 
Add a Gutenberg block similar to the core Paid Memberships Pro blocks: 
![image](https://user-images.githubusercontent.com/4752949/92498116-85f89400-f1fa-11ea-878b-db0804dba8e6.png)

**Comment by MaximilianoRicoTabo** [comment]
taking this one too

**Comment by MaximilianoRicoTabo** [comment]
https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/pull/58
