### ISSUE TITLE
Doesn't honor order from "Membership Levels" tab

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/pmpro-advanced-levels-shortcode#4]
Unless a user specifies the levels attribute, one would expect the order from the `admin.php?page=pmpro-membershiplevels` to be respected. At present, the add-on will only use the levels sorted by membership ID (ascending) as per the documentation. See: http://www.paidmembershipspro.com/forums/topic/levels-page-make-compare_table-responsive/#post-50992

**Comment by kimcoleman** [comment]
Need to test but this appears complete: https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/blob/dev/templates/levels.php#L105-L125
