### ISSUE TITLE
Custom Level Cost Text will not replace text for FREE levels

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-advanced-levels-shortcode#41]
When using Advanced Levels Shortcode, the FREE levels cost text will not change when using the Custom LEvel Cost Text Add On.

<img width="471" alt="2-changedtext" src="https://user-images.githubusercontent.com/8083630/136456274-544ad9d4-2ed3-4138-ae1e-d45cea5d34cb.png"
<img width="560" alt="1-text-should-change" src="https://user-images.githubusercontent.com/8083630/136456290-28cada81-cb05-4146-b650-c44d7f935644.png">
>

The plugin is keeping the FREE wording here.
https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/blob/b36844f3adfba833bec43f21bb9bf559b54e369a/templates/levels-compare_table.php#L32-L46

**Comment by kimcoleman** [comment]
Feels like the best path here is build in compat for Level Cost Text. If cost text is filtered by that plugin, use that text. Otherwise lets still adjust back as currently does in this Add On.

**Comment by MaximilianoRicoTabo** [comment]
https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/pull/55
