### ISSUE TITLE
Comparing: if levels ids attribute is not added , no titles or buttons appear.

### ISSUE THREAD

**Issue by kimwhite** [strangerstudios/pmpro-advanced-levels-shortcode#46]
If you don't add the level ids EX: 'levels="1,2"' to your shortcode when comparing, the Level name and button do not appear.

![levels-example](https://user-images.githubusercontent.com/8083630/217862126-c89e8998-4eb0-497c-95f5-518dc16c9473.png)

It should default to all levels if this attribute is missing.

**Comment by MaryOJob** [comment]
Note: This is also happening when using the PMPro Advanced Levels Shortcode alone and with no added attributes. Adding the level IDs fixes this issue.
Moderators Only: #477821

**Comment by michaelbeil** [comment]
Another customer ran into this (ticket 479542).
