### ISSUE TITLE
compare_table layout doesn't honor pmpro_levels_array filter

### ISSUE THREAD

**Issue by eighty20results** [strangerstudios/pmpro-advanced-levels-shortcode#5]
When applying the 'levels' array, certain membership levels may be excluded from the list of levels in spite of what the compare attribute in the `pmpro_advanced_levels shortcode` is configured to do. As a result, the table can look somewhat ugly (contains the checkmarks, but not the actual level description/price/etc.

I would have expected the shortcode to fully honor the filter, or completely ignore it.

**Comment by strangerstudios** [comment]
Believe you fixed this one recently.
