### ISSUE TITLE
Discount codes incorrectly applied when there's more than one shortcode instance

### ISSUE THREAD

**Issue by dwanjuki** [strangerstudios/pmpro-advanced-levels-shortcode#52]
**Describe the bug**
When the `[pmpro_advanced_levels]` shortcode is added to a page with the `discount` parameter set, any subsequent uses of the shortcode on the page have the first shortcode's discount code applied to the URL.

**To Reproduce**
1. Add one `[pmpro_advanced_levels]` shortcode to a page. Add the `discount_code` attribute and set a discount code.
2. Add a second `[pmpro_advanced_levels]` shortcode, do not specify a discount code.
3. Publish and view the page
4. See that both shortcode's URLs have a `discount_code` parameter set

**Expected behavior**
Second shortcode's level URL should not have a discount code parameter.

**WordPress Environment**
<details>
```
WP 6.2.2
PMPro 2.11
Advanced Levels Page Shortcode 0.2.5
```
</details>

**Comment by dwanjuki** [comment]
Came up in ticket #500898 (Mods)

**Comment by MaximilianoRicoTabo** [comment]
can't assign myself so saying here i'm taking this one.

**Comment by MaximilianoRicoTabo** [comment]
https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/pull/56
