### ISSUE TITLE
Enhancement: Allow additional HTML tags in the level cost 

### ISSUE THREAD

**Issue by dwanjuki** [strangerstudios/pmpro-advanced-levels-shortcode#53]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use additional HTML tags in the _level cost_, for greater flexibility in styling.

**Describe the solution you'd like**
Currently, other shortcode text like level description and expiration messages can be configured to allow more HTML tags using the `pmproal_allowed_html` filter. Apply the `pmproal_allowed_html` filter to the level cost text output as well.

**Additional context**
Mods: Ticket #500898

**Comment by MaximilianoRicoTabo** [comment]
Taking this one. Added the issue to the trello card

**Comment by MaximilianoRicoTabo** [comment]
https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/pull/57
