### ISSUE TITLE
French translation files

### ISSUE THREAD

**Issue by paramedicquebec** [strangerstudios/pmpro-advanced-levels-shortcode#7]
Here's the french translation for this plugin

[pmproal-fr_FR.zip](https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/files/253712/pmproal-fr_FR.zip)

**Comment by strangerstudios** [comment]
Added. Thanks!

https://github.com/strangerstudios/pmpro-advanced-levels-shortcode/commit/3d8fb268dc8c14f7154f74d3fdde342a6f7262fb
